### ISSUE TITLE
Statblock Importer Bugs (launch bugs)

### ISSUE THREAD

**Issue by TheXanathar** [cynicaloptimist/send-to-improved-initiative#1]
I've only used the importer a few times, however I've seen the following.

#1 - the most prevalent issue is capturing the "Skills" section.  I have either had no skills captured in the importer, or more common is the Saving Throws are copied over into the skill section.

#2 - handling damage resistances - Typically WoTC  use a semicolon (;) prior to the standard damage resistance of "Bludgeoning, Piercing, and Slashing from Nonmagical Attacks".  It seems that the importer ignores this, and instead picks up on commas (,) instead to separate out different line items.  Which is fine for everything else, except this well redundant part of statblocks.  Maybe an exception can be made for the Damage Resistances portion to filter out at semicolons as well.

#3 - not a bug, but will force extra work.  While the JSON does capture descriptions, it doesn't separate them by carriage/line return like in other portions of the statblock.  It also doesn't capture if any of the text is bold, italic or both.  Not a big deal as the text/data is captured, but it would require reformatting inside improved initiative to show distinctions between paragraphs.

Other than that, everything seems to be working awesome, great job and keep up the good work Evan!

Now if you could only get it to parse PDF's...

**Comment by cynicaloptimist** [comment]
Thanks Xanathar! I've fixed all three of these issues in tonight's release.
