### ISSUE TITLE
Source includes page number, creating unique source

### ISSUE THREAD

**Issue by SpartanSamuel** [cynicaloptimist/send-to-improved-initiative#2]
When importing the source, it includes the page number, and that becomes a "unique" source when sorting creatures in Improved Initiative. Could the source be imported sans page number?

**Comment by TheXanathar** [comment]
Seconded, also not all sources will have this, seems like true monster manuals do though, probably due to size

**Comment by SpartanSamuel** [comment]
Even within a source it's not consistent. For example, Eberron's Clawfoot doesn't have a page number, but all the other creatures do.

**Comment by cynicaloptimist** [comment]
This will be fixed on the Improved Initiative side of things by omitting page number when sorting.
