### ISSUE TITLE
Option to not import descriptions

### ISSUE THREAD

**Issue by SpartanSamuel** [cynicaloptimist/send-to-improved-initiative#3]
Is an option to disable importing the description feasible? When I run a session, Improved Initiative is competing for screen real estate so I prefer to keep all non-combat centric details omitted.

**Comment by TheXanathar** [comment]
My opinion fir what it's worth, I'd rather have it and delete it then not have it at all.

**Comment by SpartanSamuel** [comment]
Yeah, it's definitely a personal preference. The thing that made me think of it was Eberron's first creature, Belashyrra. Her description is longer than her actual stat block. With Stats and Saves being put at the bottom for the current player's turn while they're normal for the selected player's turn, it gets a bit frustrating having to scroll to get to the stats in these scenarios.
